NETWORK_PASSPHRASE="Public Global Stellar Network ; February 2022"
SIGNING_KEY="GCFRHDNGUC73MHZLUOLQJWOFI4Y3LMBIKAHWCDL4DCOKEOHH3O5EKALA"
ACCOUNTS=[
"GCETZ7U6Q5GSPALAJDB7PZXA2T73G5ATOGMXKYTIJCVOZTPDEWUQKALA"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="OpenBets"
ORG_DBA="OpenBets"
ORG_LOGO="https://i.imgur.com/yR6B03D.png"
ORG_DESCRIPTION="P2P"
ORG_PHYSICAL_ADDRESS="Westside, Shores, HI 96707, United States"
ORG_TELEGRAM="t.me/official_kala_community"
ORG_OFFICIAL_EMAIL="theesupremekai@gmail.com"

[[PRINCIPALS]]
name="Dickie"
email="theesupremekai@gmail.com"
github="SupremeKai69"
github="Danejw"

[[CURRENCIES]]
code="KALA"
issuer="GCETZ7U6Q5GSPALAJDB7PZXA2T73G5ATOGMXKYTIJCVOZTPDEWUQKALA"
display_decimals=3
name="KALA Tokens"
conditions="There will only ever be 1,000,000,000 KALA tokens in existence. We will distribute the revenue during special events only"
image="https://i.imgur.com/33EbOKI.png"
